[package]
name = "ergvein-rusty"
version = "0.2.0"
authors = ["Anton Gushcha <ncrashed@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin =  { version = "^0.26", features = [ "rand" ] }
bitcoin_hashes = "^0.9"
bitcoin-utxo = { git = "https://github.com/ncrashed/bitcoin-utxo" }
# bitcoin-utxo = { path = "../bitcoin-utxo" }
byteorder = "1"
bytes = "1"
chrono = "^0.4"
clap = "2.33.3"
dashmap = "^4.0"
ergvein-filters = { git = "https://github.com/ncrashed/ergvein-filters" }
ergvein-protocol = { git = "https://github.com/ncrashed/ergvein-protocol" }
futures = "0.3"
hex = "0.4"
rand = "0.8.3"
reqwest = { version = "0.11.2", features = [ "json" ] }
rocksdb = "0.15.0"
serde = { version = "1.0.124", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
tokio-util = { version = "0.6", features = [ "codec" ] }
