[package]
name = "ergvein-rusty"
version = "0.1.0"
authors = ["Anton Gushcha <ncrashed@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoin =  { version = "^0.26", features = [ "rand" ] }
bitcoin_hashes = "^0.9"
bitcoin-utxo = { git = "https://github.com/ncrashed/bitcoin-utxo" }
ergvein-filters = { git = "https://github.com/ncrashed/ergvein-filters" }
chrono = "^0.4"
dashmap = "^4.0"
futures = "0.3"
rocksdb = "0.15.0"
tokio = { version = "1", features = ["full"] }
hex = "0.4"
