on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to container registry
        uses: docker/login-action@v1
        with:
          username: ergvein
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: ${{ github.event_name == 'pull_request' && 'false' || 'true' }}
          pull: true
          tags: |
            ergvein/ergvein-index-server:rusty-${{ github.sha }}
            ergvein/ergvein-index-server:rusty
          cache-from: type=registry,ref=ergvein/ergvein-index-server:rusty
          cache-to: type=inline
